#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/private/tmp/guilda-visual-audit-modules/.pnpm/nuxt@4.5.2_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+plugin-syntax-typ_737b9510db97af48665932fec1fb5f5b/node_modules/nuxt/node_modules:/private/tmp/guilda-visual-audit-modules/.pnpm/nuxt@4.5.2_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+plugin-syntax-typ_737b9510db97af48665932fec1fb5f5b/node_modules:/private/tmp/guilda-visual-audit-modules/.pnpm/node_modules"
else
  export NODE_PATH="/private/tmp/guilda-visual-audit-modules/.pnpm/nuxt@4.5.2_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+plugin-syntax-typ_737b9510db97af48665932fec1fb5f5b/node_modules/nuxt/node_modules:/private/tmp/guilda-visual-audit-modules/.pnpm/nuxt@4.5.2_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+plugin-syntax-typ_737b9510db97af48665932fec1fb5f5b/node_modules:/private/tmp/guilda-visual-audit-modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../../../private/tmp/guilda-visual-audit-modules/.pnpm/nuxt@4.5.2_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+plugin-syntax-typ_737b9510db97af48665932fec1fb5f5b/node_modules/nuxt/bin/nuxt.mjs" "$@"
else
  exec node  "$basedir/../../../../../../../../private/tmp/guilda-visual-audit-modules/.pnpm/nuxt@4.5.2_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+plugin-syntax-typ_737b9510db97af48665932fec1fb5f5b/node_modules/nuxt/bin/nuxt.mjs" "$@"
fi
